export default {
  UPDATE_PROCESS: 'UPDATE_PROCESS',
  UPDATE_STATUS: 'UPDATE_STATUS',
  UPDATE_ROLE: 'UPDATE_ROLE',
  UPDATE_TYPE: 'UPDATE_TYPE',
  UPDATE_SOURCE: 'UPDATE_SOURCE',
  UPDATE_BTSID: 'UPDATE_BTSID',
  UPDATE_SCHEDULE: 'UPDATE_SCHEDULE'
};
